spring:
  datasource:
    reporting:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://10.104.169.175:3306/REPORTING?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
      username: root
      password: kingdee@8349
      hikari:
        maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟
        maximumPoolSize: 100 #连接池中允许的最大连接数。缺省值：10
    logging: 
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://10.66.121.198:3306/LOG?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
      username: root
      password: kingdee@8349
      hikari:
        maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟
        maximumPoolSize: 100 #连接池中允许的最大连接数。缺省值：10
